Rename dick to FS for clarity
Signed-off-by: Benoit Donneaux <benoit@leastauthority.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,8 +1,8 @@
 name: 'mount-tmpfs'
-description: 'Create and mount a temporary disk in memory'
+description: 'Create and mount a temporary file system in memory'
 inputs:
   size:
-    description: Disk size in MB (>= 1)
+    description: FS size in MB (>= 1)
     required: true
     default: 1
   root:
@@ -25,12 +25,12 @@ runs:
       run: |
         UUID="$(uuidgen)"
         MNT="${{ inputs.root }}/${UUID}"
-        echo ":rocket: Temp disk ${MNT} creation started" >> $GITHUB_STEP_SUMMARY
+        echo ":rocket: Temp FS ${MNT} creation started" >> $GITHUB_STEP_SUMMARY
         sudo mkdir -p "${MNT}" \
-        && echo ":heavy_check_mark: Temp disk mount point creation succeeded" >> $GITHUB_STEP_SUMMARY \
-        || { echo ":x: Temp disk  mount point creation failed" >> $GITHUB_STEP_SUMMARY; exit 1; }
+        && echo ":heavy_check_mark: Temp FS mount point creation succeeded" >> $GITHUB_STEP_SUMMARY \
+        || { echo ":x: Temp FS  mount point creation failed" >> $GITHUB_STEP_SUMMARY; exit 1; }
         sudo mount -o size=${{ inputs.size }},uid=$(id -u) -t tmpfs tmpfs "${MNT}" \
-        && echo ":heavy_check_mark: Temp disk mount operation succeeded" >> $GITHUB_STEP_SUMMARY \
-        || { echo ":x: Temp disk mount operation failed" >> $GITHUB_STEP_SUMMARY; exit 1; } 
+        && echo ":heavy_check_mark: Temp FS mount operation succeeded" >> $GITHUB_STEP_SUMMARY \
+        || { echo ":x: Temp FS mount operation failed" >> $GITHUB_STEP_SUMMARY; exit 1; } 
         echo "uuid=${UUID}" >> $GITHUB_OUTPUT
         echo "mnt=${MNT}" >> $GITHUB_OUTPUT
