Fix proper exit and expand to all tests
Signed-off-by: Benoit Donneaux <benoit@leastauthority.com>

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -52,6 +52,7 @@ jobs:
             exit 1
           else
             echo ":heavy_check_mark: Test succeeded" >> $GITHUB_STEP_SUMMARY
+          fi
 
   test_size:
     name: Test size
@@ -60,14 +61,37 @@ jobs:
       - uses: actions/checkout@v3
 
       - name: Call action with size
-        id: test
+        id: call
         uses: ./
         with:
           size: 4
 
-      - name: Cleanup
+      - name: Verify FS
+        id: verify
         run: |
-          sudo umount "${{ steps.test.outputs.mnt }}"
+          cat <<EOF > "${{  steps.call.outputs.mnt }}/content"
+          ${{ env.TEST_CONTENT }}
+          EOF
+          test $(cat "${{  steps.call.outputs.mnt }}/content") = "${{ env.TEST_CONTENT }}""
+        continue-on-error: true
+
+      - name: Cleanup
+        id: cleanup
+        run: |
+          sudo umount "${{ steps.call.outputs.mnt }}"
+        continue-on-error: true
+
+      - name: Proper exit
+        run: |
+          if [ ${{ steps.call.outcome }} != 'success' \
+                -o steps.verify.outcome }} != 'success' \
+                -o steps.cleanup.outcome }} != 'success' ]
+          then
+            echo ":x: Test failed" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          else
+            echo ":heavy_check_mark: Test succeeded" >> $GITHUB_STEP_SUMMARY
+          fi
   test_root:
     name: Test root
     runs-on: ubuntu-latest
@@ -75,11 +99,34 @@ jobs:
       - uses: actions/checkout@v3
 
       - name: Call action with root
-        id: test
+        id: call
         uses: ./
         with:
           root: ./test_root
 
-      - name: Cleanup
+      - name: Verify FS
+        id: verify
         run: |
-          sudo umount "${{ steps.test.outputs.mnt }}"
+          cat <<EOF > "${{  steps.call.outputs.mnt }}/content"
+          ${{ env.TEST_CONTENT }}
+          EOF
+          test $(cat "${{  steps.call.outputs.mnt }}/content") = "${{ env.TEST_CONTENT }}""
+        continue-on-error: true
+
+      - name: Cleanup
+        id: cleanup
+        run: |
+          sudo umount "${{ steps.call.outputs.mnt }}"
+        continue-on-error: true
+
+      - name: Proper exit
+        run: |
+          if [ ${{ steps.call.outcome }} != 'success' \
+                -o steps.verify.outcome }} != 'success' \
+                -o steps.cleanup.outcome }} != 'success' ]
+          then
+            echo ":x: Test failed" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          else
+            echo ":heavy_check_mark: Test succeeded" >> $GITHUB_STEP_SUMMARY
+          fi
